version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tresbros_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD
      POSTGRES_DB: tresbros
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tresbros_backend
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=tresbros;Username=postgres;Password=YOUR_POSTGRES_PASSWORD
    volumes:
      - ./backend/appsettings.json:/app/appsettings.json
    ports:
      - "5052:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tresbros_frontend
    environment:
      - BACKEND_URL=http://backend:8080
      - NEXT_PUBLIC_MIDTRANS_CLIENT_KEY=SB-Mid-client-3c-KuTSEjRrpPILS
    ports:
      - "3005:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
